# Generated by Django 3.1.6 on 2021-02-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
    ]
