# Generated by Django 3.1.6 on 2021-08-29 10:49

from django.db import migrations
import i_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('i_auth', '0002_user_balance'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', i_auth.models.CustomUserManager()),
            ],
        ),
    ]
