# Generated by Django 3.1.6 on 2021-03-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_accounts', '0002_auto_20210321_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
