# Generated by Django 3.1.6 on 2021-04-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i_accounts', '0003_account_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='login',
            new_name='username',
        ),
    ]
