# Generated by Django 3.1.6 on 2021-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_accounts', '0004_auto_20210411_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
