# Generated by Django 3.1.6 on 2021-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type_of',
            field=models.IntegerField(choices=[(0, 'Лайки по лайктайму'), (1, 'Лайки по хэштегам'), (2, 'Подписки по хэштегам'), (3, 'Отписка от неподписаных'), (4, 'Отписка от всех'), (5, 'Игра')]),
        ),
    ]
