# Generated by Django 3.1.6 on 2021-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_job', '0003_auto_20210411_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
