# Generated by Django 3.1.6 on 2021-04-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i_job', '0005_auto_20210425_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='winner',
            new_name='vinner',
        ),
    ]
